
export const LOGIN = "/api/user/login"
export const REGISTER = "/api/user/register"
export const GET_AUTH_USER = "/api/user/getAuth"
export const SIGN_OUT_USER = "/api/user/signout"
export const CREATE_CHAT = "/api/chat/create"
export const GET_CHATS = "/api/chat/get"
export const GET_MESSAGES = "/api/message/getChatMessage/"
export const PROMPT = "/api/message/prompt"
export const UPDATE_PASSWORD = "/api/user/updatePassword"
export const UPDATE_USER = "/api/user/updateInformation"